name: Build SwiftShader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: lukka/get-cmake@v3

    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure project
      run: cmake -B build -S .

    - name: Build SwiftShader
      run: cmake --build build --parallel

    - name: look
      run: dir
